USE [master];
GO

IF NOT EXISTS (SELECT * FROM sys.sql_logins WHERE name = '$MSSQL_USER')
BEGIN
    CREATE LOGIN [${MSSQL_USER}] WITH PASSWORD = '${MSSQL_PASS}', CHECK_POLICY = OFF;
    ALTER SERVER ROLE [sysadmin] ADD MEMBER [${MSSQL_USER}];
END
GO


CREATE DATABASE $MSSQL_DB;
GO

USE ${MSSQL_DB};
CREATE USER [${MSSQL_USER}] FROM LOGIN [${MSSQL_USER}];
GO

CREATE SCHEMA ${MSSQL_SCHEMA} AUTHORIZATION ${MSSQL_USER};
GO

